# Supabase Configuration for Deligate.it
project_id = "deligate-it"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[storage]
enabled = true
file_size_limit = 52428800  # 50MB

[auth]
enabled = true
site_url = "https://deligate.it"
additional_redirect_urls = ["https://app.deligate.it", "http://localhost:3000"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
otp_length = 6

[auth.external.github]
enabled = true

[auth.external.google]
enabled = true