server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Application logs
  - job_name: labelmintit-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: labelmintit-backend
          __path__: /var/log/labelmintit/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            request_id: request_id
      - timestamp:
          format: RFC3339Nano
          source: timestamp
      - labels:
          level:
      - output:
          source: message

  # Nginx access logs
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - regex:
          expression: '(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>.+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>.*)" "(?P<http_user_agent>.*)"'
      - timestamp:
          format: '02/Jan/2006:15:04:05 -0700'
          source: time_local
      - labels:
          method:
          status:
          remote_addr:
      - output:
          source: message

  # Nginx error logs
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          __path__: /var/log/nginx/error.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<severity>\w+)\] (?P<pid>\d+)#(?P<tid>\d+): (?P<message>.*)'
      - timestamp:
          format: '2006/01/02 15:04:05'
          source: timestamp
      - labels:
          severity:
          pid:
      - output:
          source: message

  # System logs
  - job_name: system
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    pipeline_stages:
      - regex:
          expression: '(?P<time>\w+\s+\d+\s+\d+:\d+:\d+) (?P<host>\S+) (?P<service>\S+): (?P<message>.*)'
      - timestamp:
          format: 'Jan 2 15:04:05'
          source: time
      - labels:
          service:
          host:
      - output:
          source: message

  # Docker container logs
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        port: 80
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: time
            message: log
            container_name: container_name
      - timestamp:
          format: RFC3339Nano
          source: timestamp
      - labels:
          level:
          container_name:
      - output:
          source: message

  # PostgreSQL logs
  - job_name: postgresql
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgresql
          __path__: /var/log/postgresql/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+ \w+) \[(?P<pid>\d+)\] (?P<level>\w+):\s+(?P<message>.*)'
      - timestamp:
          format: '2006-01-02 15:04:05.000 MST'
          source: timestamp
      - labels:
          level:
          pid:
      - output:
          source: message

  # Redis logs
  - job_name: redis
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          __path__: /var/log/redis/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d+:\d+:\d+) (?P<level>\d+)#(?P<pid>\d+) (?P<message>.*)'
      - timestamp:
          format: '2006-01-02 15:04:05'
          source: timestamp
      - labels:
          level:
          pid:
      - output:
          source: message

# Global configuration
limit_config:
  read_buffer_size: 4096
  line_limit: 2048
  max_line_size: 1048576
  backfill: true

# Rate limiting
rate_config:
  enabled: true
  burst: 1000
  rate: 100