groups:
  - name: labelmint.infrastructure
    rules:
      # Container Health Alerts
      - alert: ContainerDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "Container {{ $labels.job }} on {{ $labels.instance }} is down"
          description: "Container {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/container-down.md"

      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 30s
        labels:
          severity: critical
          service: postgresql
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL database has been down for more than 30 seconds."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/postgresql-down.md"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 30s
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis cache is down"
          description: "Redis cache has been down for more than 30 seconds."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/redis-down.md"

      - alert: MinIODown
        expr: up{job="minio"} == 0
        for: 1m
        labels:
          severity: critical
          service: minio
        annotations:
          summary: "MinIO object storage is down"
          description: "MinIO object storage has been down for more than 1 minute."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/minio-down.md"

      # Resource Usage Alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }} for more than 5 minutes."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/high-cpu.md"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }} for more than 5 minutes."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/high-memory.md"

      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} for more than 5 minutes."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/high-disk.md"

      - alert: CriticalDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100 > 95
        for: 1m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Critical disk usage on {{ $labels.instance }}"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} for more than 1 minute."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/critical-disk.md"

      # Application-specific Alerts
      - alert: DatabaseConnectionFailure
        expr: pg_stat_activity_count > 100
        for: 2m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "High number of database connections"
          description: "PostgreSQL has {{ $value }} active connections for more than 2 minutes."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/db-connections.md"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis memory usage is {{ $value | humanizePercentage }} for more than 5 minutes."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/redis-memory.md"

      # Service-specific Alerts
      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 1m
        labels:
          severity: warning
          service: grafana
        annotations:
          summary: "Grafana monitoring dashboard is down"
          description: "Grafana has been down for more than 1 minute."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/grafana-down.md"

      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 30s
        labels:
          severity: critical
          service: prometheus
        annotations:
          summary: "Prometheus monitoring server is down"
          description: "Prometheus has been down for more than 30 seconds."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/prometheus-down.md"

      # Network Alerts
      - alert: HighNetworkTraffic
        expr: irate(node_network_receive_bytes_total{device!="lo"}[5m]) * 8 > 100000000
        for: 5m
        labels:
          severity: warning
          service: network
        annotations:
          summary: "High network traffic on {{ $labels.device }}"
          description: "Network receive traffic is {{ $value | humanizeBits }} on {{ $labels.device }} for more than 5 minutes."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/high-network.md"

      # Container Resource Alerts
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total{name=~"labelmint.*"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "High CPU usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} CPU usage is {{ $value }}% for more than 5 minutes."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/container-cpu.md"

      - alert: ContainerHighMemory
        expr: container_memory_usage_bytes{name=~"labelmint.*"} / container_spec_memory_limit_bytes{name=~"labelmint.*"} * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "High memory usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} memory usage is {{ $value }}% for more than 5 minutes."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/container-memory.md"

  - name: labelmint.availability
    rules:
      # Service Availability Alerts
      - alert: ServiceUnavailable
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "Service {{ $labels.instance }} is unavailable"
          description: "Health check failed for {{ $labels.instance }} for more than 1 minute."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/service-unavailable.md"

      - alert: SlowResponse
        expr: probe_duration_seconds > 5
        for: 2m
        labels:
          severity: warning
          service: "{{ $labels.job }}"
        annotations:
          summary: "Slow response from {{ $labels.instance }}"
          description: "Response time is {{ $value }}s from {{ $labels.instance }} for more than 2 minutes."
          runbook_url: "https://github.com/labelmint/labelmint/runbooks/slow-response.md"