# Unified Loki Configuration for LabelMint
# Centralized log aggregation and management

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

# Common configuration
common:
  instance_interface_names: ['eth0']
  path_prefix: /loki
  storage:
    s3:
      s3: null
      insecure: false
      s3forcepathstyle: false
      bucketnames: labelmint-loki-chunks
      access_key_id: ${MINIO_ACCESS_KEY}
      secret_access_key: ${MINIO_SECRET_KEY}
      endpoint: http://minio:9000
      region: us-east-1
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# Query configuration
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

# Scheduler configuration
scheduler:
  ring:
    kvstore:
      store: inmemory

# Ingester configuration
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
    num_recent_log_lines: 100
    heartbeat_period: 5s
    heartbeat_timeout: 1m
    join_after: 0s
    observe_period: 5s
    min_ready_duration: 15s
    flush_check_period: 30s
    flush_period: 1m
    chunk_idle_period: 30m
    chunk_retain_period: 30s
    max_transfer_retries: 0
    sync_period: 0s

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 0s
  chunk_target_size: 1048576
  chunk_cache_size: 500
  write_buffer_size: 104857600
  max_chunk_age: 1h
  chunk_gc_policy:
    max_age: 168h  # 7 days
    retention_period: 336h  # 14 days

# Schema configuration
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h

# Limits configuration
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  max_query_length: 721h
  max_query_parallelism: 32
  cardinality_limit: 100000
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  per_stream_rate_limit: 16MB
  per_stream_rate_limit_burst: 32MB

# Table manager configuration
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

# Ruler configuration
ruler:
  storage:
    s3:
      s3: null
      insecure: false
      s3forcepathstyle: false
      bucketnames: labelmint-loki-ruler
      access_key_id: ${MINIO_ACCESS_KEY}
      secret_access_key: ${MINIO_SECRET_KEY}
      endpoint: http://minio:9000
      region: us-east-1
  enable_alertmanager_v2: true
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  rule_path: /rules
  poll_interval: 1m

# By default, Loki will send anonymous usage data to Grafana Labs.
# To disable, set analytics.enabled to false in your configuration.
analytics:
  enabled: false
  reporting_enabled: false