apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: labelmintit
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "50"
spec:
  tls:
  - hosts:
    - staging.labelmintit.com
    secretName: labelmintit-staging-tls
  rules:
  - host: staging.labelmintit.com