apiVersion: v1
kind: Service
metadata:
  name: labelmint-backend-service
  namespace: labelmint
  labels:
    app: labelmint-backend
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: labelmint-backend
    component: backend