apiVersion: apps/v1
kind: Deployment
metadata:
  name: labelmintit
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: labelmintit-app
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: NODE_ENV
          value: "staging"
        - name: LOG_LEVEL
          value: "debug"