global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@labelmint.com'
  smtp_auth_username: 'alerts@labelmint.com'
  smtp_auth_password: 'your-app-password'
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m
    - match:
        severity: info
      receiver: 'info-alerts'
      repeat_interval: 2h

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
  - name: 'default'
    email_configs:
      - to: 'ops@labelmint.com'
        subject: '[LabelMint] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}
    slack_configs:
      - channel: '#alerts'
        title: 'LabelMint Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Labels:* {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'ops@labelmint.com,cto@labelmint.com'
        subject: '[CRITICAL] LabelMint Alert: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT - IMMEDIATE ACTION REQUIRED

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Service: {{ .Labels.service }}
          Started: {{ .StartsAt }}
          {{ end }}

          Please investigate immediately.
    slack_configs:
      - channel: '#critical'
        title: '🚨 CRITICAL LabelMint Alert'
        color: 'danger'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          *Service:* {{ .Labels.service }}
          *Runbook:* <https://runbooks.labelmint.com/alerts/{{ .Labels.alertname }}|Click here>
          {{ end }}
    webhook_configs:
      - url: 'http://pagerduty-webhook:8080/v1/alert'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@labelmint.com'
        subject: '[WARNING] LabelMint Alert: {{ .GroupLabels.alertname }}'
        body: |
          Warning Alert - Please investigate within 30 minutes

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Service: {{ .Labels.service }}
          {{ end }}
    slack_configs:
      - channel: '#warnings'
        title: '⚠️ LabelMint Warning'
        color: 'warning'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}

  - name: 'info-alerts'
    slack_configs:
      - channel: '#info'
        title: 'ℹ️ LabelMint Info'
        color: 'good'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

templates:
  - '/etc/alertmanager/templates/*.tmpl'