apiVersion: 1

datasources:
  # Prometheus Datasource
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    editable: true

  # Loki Datasource
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
          datasource: "Jaeger"
    editable: true

  # Jaeger Datasource
  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger-all-in-one:16686
    access: proxy
    editable: true

  # Graphite (for compatibility)
  - name: Graphite
    type: graphite
    uid: graphite
    url: http://graphite:8080
    access: proxy
    editable: false

  # Elasticsearch (if used)
  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    database: "logs-*"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.0.0"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"
    editable: true