---
# Production resource limits
apiVersion: v1
kind: LimitRange
metadata:
  name: labelmintit-prod-limits
  labels:
    env: production
spec:
  limits:
  - default:
      cpu: "2000m"
      memory: "2Gi"
      ephemeral-storage: "5Gi"
    defaultRequest:
      cpu: "500m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
    type: Container
  - max:
      cpu: "4000m"
      memory: "4Gi"
      ephemeral-storage: "20Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
      ephemeral-storage: "100Mi"
    type: Container

---
# Production resource quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: labelmintit-prod-quota
  labels:
    env: production
spec:
  hard:
    requests.cpu: "20"
    requests.memory: "40Gi"
    limits.cpu: "40"
    limits.memory: "80Gi"
    pods: "100"
    services: "20"
    secrets: "50"
    configmaps: "50"
    persistentvolumeclaims: "20"
    services.loadbalancers: "5"
    count/services.loadbalancers: "5"

---
# Production node pool resource limits
apiVersion: v1
kind: ResourceQuota
metadata:
  name: labelmintit-prod-node-pool-quota
  labels:
    env: production
    component: node-pool
spec:
  scopeSelector:
    matchExpressions:
    - operator: In
      values: ["production"]
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"