// Generated TypeScript types for Deligate.it
// Auto-generated by setup script

export interface User {
  id: string;
  email: string;
  email_verified: boolean;
  first_name: string;
  last_name: string;
  phone?: string;
  phone_verified?: boolean;
  avatar_url?: string;
  role: 'USER' | 'ADMIN' | 'SUPER_ADMIN' | 'SUPPORT';
  status: 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'DELETED' | 'BANNED';
  auth_provider: 'EMAIL' | 'GOOGLE' | 'GITHUB' | 'TELEGRAM';
  created_at: string;
  updated_at: string;
}

export interface UserWallet {
  id: string;
  user_id: string;
  network: 'mainnet' | 'testnet';
  version: 'v3R2' | 'v4R2' | 'telegram';
  address: string;
  public_key: string;
  is_active: boolean;
  is_default: boolean;
  balance: number;
  usdt_balance: number;
  created_at: string;
  updated_at: string;
}

export interface Transaction {
  id: string;
  from_wallet_id?: string;
  to_wallet_id?: string;
  from_address: string;
  to_address: string;
  amount: number;
  token_type: 'TON' | 'USDT';
  transaction_type: 'deposit' | 'withdrawal' | 'transfer' | 'payment' | 'refund' | 'fee';
  message?: string;
  status: 'pending' | 'confirmed' | 'failed' | 'cancelled' | 'refunded';
  tx_hash?: string;
  fee: number;
  created_at: string;
  confirmed_at?: string;
}

export interface Database {
  public: {
    Tables: {
      users: User;
      user_wallets: UserWallet;
      transactions: Transaction;
    };
  };
}