apiVersion: v1
kind: Namespace
metadata:
  name: labelmint
  labels:
    name: labelmint
    environment: production
    project: labelmint
  annotations:
    description: "LabelMint application namespace"