auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  alertmanager_url: http://alertmanager:9093

analytics:
  reporting_enabled: false

query_range:
  split_queries_by_interval: true
  max_query_parallelism: 32
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      ttl: 24h
      max_size_items: 100000

frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  max_outstanding_requests_per_tenant: 4096
  query_stats_enabled: true

querier:
  query_ingester_timeout: 5m
  query_timeout: 5m
  max_concurrent_queries: 10
  engine:
    max_look_back_period: 0s

ingester_client:
  remote_timeout: 5s
  grpc_client_config:
    max_send_msg_size: 10485760
    max_recv_msg_size: 10485760
    use_compression: true

memberlist:
  join_members:
    - localhost:7946
  dead_node_reclaim_time: 30s
  left_node_timeout: 30s
  gossip_interval: 2s
  push_pull_interval: 30s
  enable_node_prometheus: true

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  delete_request_cancel_period: 24h
  delete_request_store: s3

limits_config:
  per_tenant_override_config: "/loki/overrides.yaml"

wal:
  enabled: true
  dir: /loki/wal

frontend_worker:
  frontend_address: 127.0.0.1:9095
  parallelism: 2