# Pod Security Policy for LabelMint
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: labelmint-psp
  labels:
    app: labelmint
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
---
# Role for PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: labelmint-psp-role
  namespace: labelmint
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - labelmint-psp
---
# Role binding for PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: labelmint-psp-binding
  namespace: labelmint
roleRef:
  kind: Role
  name: labelmint-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: labelmint-service-account
    namespace: labelmint