name: Simple Test Workflow

on:
  push:
    branches: [develop, main]

jobs:
  test-basic:
    name: Basic Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Echo success
        run: |
          echo "✅ Simple test workflow is working!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"