apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: labelmintit-staging

namespace: staging

bases:
  - ../../base

commonLabels:
  env: staging

commonAnnotations:
  config.kubernetes.io/origin: "staging"

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

patchesJson6902:
  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: labelmintit-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5

  - target:
      group: policy
      version: v1
      kind: PodDisruptionBudget
      name: labelmintit-pdb
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 1

configMapGenerator:
  - name: labelmintit-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=debug
      - CORS_ORIGINS=http://localhost:3000,https://staging.labelmintit.com
      - ENABLE_REGISTRATION=true
      - ENABLE_EMAIL_VERIFICATION=false

images:
  - name: labelmintit/app
    newTag: staging

replicas:
  - name: labelmintit
    count: 2

resources:
  - resources.yaml
  - secrets.yaml